#!/usr/bin/env python3
"""Generate the degradation table in `hailo_ops.usda`.

Every opset-17 operator the target does not implement is here, with either a rewrite into
operators it does implement, or a reason there is none. Both are entries. An operator with no
row at all would be indistinguishable from one nobody has looked at, and that ambiguity is the
thing this file exists to remove.

THE PRIMITIVES A REWRITE MAY USE are exactly the documented set -- `Layers` plus `Activations`
plus anything reachable through a `Patterns` sequence -- and nothing else. A rewrite naming an
operator that is itself unsupported and has no rewrite of its own is a rewrite that bottoms out
in nothing; `check_device_ops.py` rejects those, so the table cannot quietly rest on air.

WHY SOME HAVE NO REWRITE, and the categories are worth separating because they are not equally
permanent:

    data-dependent-shape  the output shape depends on the values, which a static dataflow
                          graph cannot express at all. Compress, NonZero, Unique.
    control-flow          If, Loop, Scan: execution that branches at runtime.
    not-a-tensor          sequence and optional types. The CONTAINER is not a tensor even
                          where its elements are, which is what the category is about.
    not-reproducible      the result depends on the environment rather than only on the
                          input, so two machines running the same graph disagree. Text
                          preprocessing belongs in a tokenizer, ahead of the graph, and the
                          ONNX ecosystem puts it in a custom-op domain that no accelerator
                          toolchain lowers.
    nondeterministic      the random family. A rewrite would have to invent an RNG, and a
                          corpus generated by one is not reproducible.
    toolchain-owns-it     the quantization operators. The compiler quantizes; emitting
                          QuantizeLinear ourselves would fight it for the same job.
    rounding              Floor, Ceil, Round, Mod. A rewrite exists on paper -- a sum of
                          clipped steps -- and `native_onehot.py` measured that family dying
                          under int8, where the amplification a step needs is exactly what
                          quantization destroys. Recorded as refused rather than absent.

Usage:
    python scripts/gen_degradations.py           # rewrite the Secondary scope in place
    python scripts/gen_degradations.py --print   # show what it would write
"""
from __future__ import annotations

import pathlib
import re
import sys

HERE = pathlib.Path(__file__).parent

#: Operators whose rewrite can be taken from ONNX's OWN function body rather than written by
#: hand. The spec ships `FunctionProto` decompositions for 21 of the 120 unsupported operators,
#: Apache-2.0, and they are authoritative where a hand-written identity is merely careful.
#:
#: `usable` bottoms out in operators the target reaches. `cast-only` needs one relabelling Cast
#: folded first -- a type promotion, not the value-changing kind that is refused. `blocked`
#: bottoms out in something unavailable, so the spec body does not help.
SPEC_BODY = {
    "Selu": "usable", "Shrink": "usable", "ThresholdedRelu": "usable", "HardSwish": "usable",
    "GreaterOrEqual": "usable", "LessOrEqual": "usable", "ReduceL1": "usable",
    "ReduceLogSum": "usable", "MeanVarianceNormalization": "usable",
    "ReduceLogSumExp": "cast-only", "HannWindow": "cast-only",
    "HammingWindow": "cast-only", "BlackmanWindow": "cast-only",
    "DynamicQuantizeLinear": "blocked",
}

#: How a rewrite is established, which is a different question from whether it is. Three tiers,
#: and the difference is how a wrong one would be caught:
#:
#:   ring         a polynomial identity a decision procedure settles. Cannot be subtly wrong --
#:                `ring` closes the goal or the claim is false. No reviewer judgement.
#:   analysis     hand-proved in Mathlib, sometimes under hypotheses that have to hold where it
#:                is used. A wrong one looks exactly like a right one until somebody reads it.
#:   approximate  not an identity. No theorem claims it is, and none should.
#:
#: Absent means not yet proved either way, which is honest rather than tidy.
PROOF = {
    "Where": "ring", "And": "ring", "Or": "ring", "Not": "ring", "Xor": "ring",
    "Sum": "ring", "Mean": "ring", "Expand": "ring", "Trilu": "ring",
    "Reciprocal": "ring", "GreaterOrEqual": "ring", "LessOrEqual": "ring",
    "Sinh": "analysis", "Cosh": "analysis", "Asinh": "analysis", "Acosh": "analysis",
    "Atanh": "analysis", "Celu": "analysis", "Selu": "analysis", "Softsign": "analysis",
    "ThresholdedRelu": "analysis", "Sign": "analysis", "ReduceProd": "analysis",
    "Sin": "approximate", "Cos": "approximate", "Tan": "approximate",
    "Asin": "approximate", "Acos": "approximate", "Atan": "approximate",
}

#: operator -> the family it belongs to. Splitting `Secondary` by category is not tidiness:
#: `trigonometric-approximate` is the only family whose rewrites are NOT identities, and
#: burying six approximations among 75 exact ones is how somebody comes to believe the whole
#: table is proved. `hyperbolic-exact` is named against it for the same reason.
CATEGORY = {'Where': 'selection', 'GreaterOrEqual': 'selection', 'LessOrEqual': 'selection', 'Sign': 'selection', 'IsNaN': 'selection', 'IsInf': 'selection', 'And': 'boolean', 'Or': 'boolean', 'Not': 'boolean', 'Xor': 'boolean', 'ReduceL1': 'reduction', 'ReduceLogSum': 'reduction', 'ReduceLogSumExp': 'reduction', 'ReduceProd': 'reduction', 'Sum': 'reduction', 'Mean': 'reduction', 'ArgMin': 'reduction', 'CumSum': 'reduction', 'GlobalAveragePool': 'pooling-normalisation', 'GlobalMaxPool': 'pooling-normalisation', 'GlobalLpPool': 'pooling-normalisation', 'LpPool': 'pooling-normalisation', 'LpNormalization': 'pooling-normalisation', 'MeanVarianceNormalization': 'pooling-normalisation', 'InstanceNormalization': 'pooling-normalisation', 'LRN': 'pooling-normalisation', 'Celu': 'activation', 'Selu': 'activation', 'HardSwish': 'activation', 'ThresholdedRelu': 'activation', 'Shrink': 'activation', 'Hardmax': 'activation', 'Softsign': 'activation', 'Sinh': 'hyperbolic-exact', 'Cosh': 'hyperbolic-exact', 'Asinh': 'hyperbolic-exact', 'Acosh': 'hyperbolic-exact', 'Atanh': 'hyperbolic-exact', 'Sin': 'trigonometric-approximate', 'Cos': 'trigonometric-approximate', 'Tan': 'trigonometric-approximate', 'Asin': 'trigonometric-approximate', 'Acos': 'trigonometric-approximate', 'Atan': 'trigonometric-approximate', 'Gather': 'indexing', 'GatherElements': 'indexing', 'GatherND': 'indexing', 'Scatter': 'indexing', 'ScatterElements': 'indexing', 'ScatterND': 'indexing', 'TopK': 'indexing', 'MaxUnpool': 'indexing', 'GridSample': 'indexing', 'Flatten': 'shape-folded', 'Squeeze': 'shape-folded', 'Unsqueeze': 'shape-folded', 'Expand': 'shape-folded', 'Tile': 'shape-folded', 'Identity': 'shape-folded', 'Constant': 'shape-folded', 'ConstantOfShape': 'shape-folded', 'Shape': 'shape-folded', 'Size': 'shape-folded', 'Range': 'shape-folded', 'EyeLike': 'shape-folded', 'Trilu': 'shape-folded', 'ReverseSequence': 'shape-folded', 'ConcatFromSequence': 'shape-folded', 'SplitToSequence': 'shape-folded', 'CastLike': 'shape-folded', 'Einsum': 'linear-transform', 'DFT': 'linear-transform', 'STFT': 'linear-transform', 'BlackmanWindow': 'linear-transform', 'HammingWindow': 'linear-transform', 'HannWindow': 'linear-transform', 'MelWeightMatrix': 'linear-transform', 'MaxRoiPool': 'linear-transform', 'RoiAlign': 'linear-transform', 'NegativeLogLikelihoodLoss': 'loss', 'SoftmaxCrossEntropyLoss': 'loss', 'TfIdfVectorizer': 'indexing'}

#: operator -> (identity, [operators the rewrite uses])
REWRITES = {
    # --- selection and comparison ---------------------------------------------------------
    "Where": ("where(c, a, b) == b + (a - b) * c, for c in {0, 1}", ["Sub", "Mul", "Add"]),
    "GreaterOrEqual": ("x >= y == 1 - (x < y)", ["Less", "Sub"]),
    "LessOrEqual": ("x <= y == 1 - (x > y)", ["Greater", "Sub"]),
    "Sign": ("sign(x) == (x > 0) - (x < 0), which is exact at zero unlike x / |x|",
             ["Greater", "Less", "Sub"]),
    "IsNaN": ("isnan(x) == 1 - (x == x); NaN is the only value not equal to itself",
              ["Equal", "Sub"]),
    "IsInf": ("isinf(x) == |x| > finite_max, with the bound a constant",
              ["Abs", "Greater"]),

    # --- boolean algebra, as arithmetic on {0, 1} -----------------------------------------
    # `boolean_arithmetic.py` is the working of these; they are exact on {0, 1} and only there.
    "And": ("a and b == a * b, on {0, 1}", ["Mul"]),
    "Or": ("a or b == a + b - a * b, on {0, 1}", ["Add", "Sub", "Mul"]),
    "Not": ("not a == 1 - a, on {0, 1}", ["Sub"]),
    "Xor": ("a xor b == a + b - 2 * a * b, on {0, 1}", ["Add", "Sub", "Mul"]),

    # --- reductions -----------------------------------------------------------------------
    "ReduceL1": ("L1(x) == sum(|x|)", ["Abs", "ReduceSum"]),
    "ReduceLogSum": ("logsum(x) == log(sum(x))", ["ReduceSum", "Log"]),
    "ReduceLogSumExp": ("logsumexp(x) == log(sum(exp(x)))", ["Exp", "ReduceSum", "Log"]),
    "ReduceProd": ("prod(x) == exp(sum(log(x))), FOR STRICTLY POSITIVE x only; a zero or a "
                   "negative makes the log undefined and this rewrite wrong",
                   ["Log", "ReduceSum", "Exp"]),
    "Sum": ("sum(a, b, ...) == a + b + ..., left-folded", ["Add"]),
    "Mean": ("mean(x_1..x_n) == (x_1 + ... + x_n) / n", ["Add", "Div"]),
    "ArgMin": ("argmin(x) == argmax(-x)", ["Neg", "ArgMax"]),
    "CumSum": ("cumsum(x) == L @ x, with L a constant lower-triangular matrix of ones. The "
               "shape is fixed, so L is a constant rather than a computation",
               ["MatMul"]),

    # --- pooling and normalisation ---------------------------------------------------------
    "GlobalAveragePool": ("global average pool == reduce mean over the spatial axes",
                          ["ReduceMean"]),
    "GlobalMaxPool": ("global max pool == reduce max over the spatial axes", ["ReduceMax"]),
    "GlobalLpPool": ("Lp pool == (sum(|x|^p))^(1/p)", ["Abs", "Pow", "ReduceSum"]),
    "LpPool": ("windowed Lp pool == (avgpool(|x|^p) * window)^(1/p)",
               ["Abs", "Pow", "AveragePool"]),
    "LpNormalization": ("x / ||x||_2 along an axis", ["ReduceL2", "Div"]),
    "MeanVarianceNormalization": ("(x - mean) / sqrt(var + eps), which is layer norm without "
                                  "the learned scale and shift", ["LayerNormalization"]),
    "InstanceNormalization": ("per-instance (x - mean) / sqrt(var + eps), then scale and shift",
                              ["ReduceMean", "Sub", "Mul", "Sqrt", "Div", "Add"]),
    "LRN": ("local response norm == x / (k + a/n * boxsum(x^2))^b, the window sum being an "
            "average pool over squares", ["Mul", "AveragePool", "Pow", "Div", "Add"]),

    # --- activations -----------------------------------------------------------------------
    "Celu": ("celu(x) == max(0, x) + min(0, a * (exp(x / a) - 1))",
             ["Relu", "Div", "Exp", "Sub", "Mul", "Min", "Add"]),
    "Selu": ("selu(x) == g * (max(0, x) + min(0, a * (exp(x) - 1)))",
             ["Relu", "Exp", "Sub", "Mul", "Min", "Add"]),
    "HardSwish": ("hardswish(x) == x * hardsigmoid(x); the target names this pattern",
                  ["Mul", "HardSigmoid"]),
    "ThresholdedRelu": ("thresholded relu(x) == x * (x > theta)", ["Greater", "Mul"]),
    "Shrink": ("shrink(x) == (x < -l)(x + b) + (x > l)(x - b)",
               ["Less", "Greater", "Add", "Sub", "Mul"]),
    "Hardmax": ("hardmax(x) == onehot(argmax(x)); the target implements OneHot natively, "
                "which is what makes this cheap rather than a tent reconstruction",
                ["ArgMax", "OneHot"]),
    "Softsign": ("x / (1 + |x|)", ["Abs", "Add", "Div"]),

    # --- trigonometry ----------------------------------------------------------------------
    # The hyperbolics are exact through Exp. The circular ones are not closed-form here, and
    # `trig_polynomial.py` is the working: a minimax polynomial after range reduction.
    "Sinh": ("sinh(x) == (exp(x) - exp(-x)) / 2, exact", ["Exp", "Neg", "Sub", "Div"]),
    "Cosh": ("cosh(x) == (exp(x) + exp(-x)) / 2, exact", ["Exp", "Neg", "Add", "Div"]),
    "Asinh": ("asinh(x) == log(x + sqrt(x^2 + 1)), exact", ["Mul", "Add", "Sqrt", "Log"]),
    "Acosh": ("acosh(x) == log(x + sqrt(x^2 - 1)), exact for x >= 1", ["Mul", "Sub", "Sqrt", "Log"]),
    "Atanh": ("atanh(x) == 0.5 * log((1 + x) / (1 - x)), exact for |x| < 1",
              ["Add", "Sub", "Div", "Log", "Mul"]),
    "Sin": ("sin(x) == x * P(x^2), a degree-9 odd polynomial. VALID ONLY ON [-pi/2, pi/2] here -- see the category warning", ["Mul", "Add"]),
    "Cos": ("cos(x) == sin(x + pi/2), same polynomial. VALID ONLY ON [-pi/2, pi/2]", ["Mul", "Add"]),
    "Tan": ("tan(x) == sin(x) / cos(x); range limited AND unbounded near pi/2",
            ["Mul", "Add", "Div"]),
    "Asin": ("asin(x) == x * P(x^2) on the principal branch", ["Mul", "Add", "Sqrt"]),
    "Acos": ("acos(x) == pi/2 - asin(x)", ["Sub", "Mul", "Add", "Sqrt"]),
    "Atan": ("atan(x) == x * P(x^2) after quadrant folding", ["Mul", "Add", "Div"]),

    # --- indexing, which is where OneHot earns its place ------------------------------------
    "Gather": ("gather(data, idx) == onehot(idx) @ data. The accelerator implements OneHot as "
               "a convolution with a delta activation, so the index is never quantised -- "
               "which is the whole reason to prefer it to a tent kernel",
               ["OneHot", "MatMul"]),
    "GatherElements": ("as Gather, along the gathered axis", ["OneHot", "MatMul"]),
    "GatherND": ("flatten the indexed axes, then Gather", ["Reshape", "OneHot", "MatMul"]),
    "Scatter": ("scatter(base, idx, upd) == base + onehot(idx)^T @ upd",
                ["OneHot", "Transpose", "MatMul", "Add"]),
    "ScatterElements": ("as Scatter, along the scattered axis",
                        ["OneHot", "Transpose", "MatMul", "Add"]),
    "ScatterND": ("flatten the indexed axes, then Scatter",
                  ["Reshape", "OneHot", "Transpose", "MatMul", "Add"]),
    "TopK": ("a bitonic sorting network of Min and Max, then Slice. The depth is O(log^2 n) "
             "and fixed, so it is a static graph; topk_bitonic.py is the working",
             ["Min", "Max", "Concat", "Slice"]),
    "MaxUnpool": ("scatter the values back to the argmax positions", ["OneHot", "MatMul"]),
    "GridSample": ("bilinear sample == gather the four corners and weight them, the gather "
                   "by OneHot", ["OneHot", "MatMul", "Mul", "Add"]),

    # --- shape plumbing, which folds at a fixed resolution -----------------------------------
    "Flatten": ("a Reshape to a known shape", ["Reshape"]),
    "Squeeze": ("a Reshape to a known shape", ["Reshape"]),
    "Unsqueeze": ("a Reshape to a known shape", ["Reshape"]),
    "Expand": ("broadcast to a known shape == multiply by a constant one-tensor", ["Mul"]),
    "Tile": ("repeat along an axis == concatenate the input with itself", ["Concat"]),
    "Identity": ("removed; it computes nothing and the consumer reads the producer directly", []),
    "Constant": ("folded into the consumer at build time; the shape is fixed", []),
    "ConstantOfShape": ("folded; the shape is known before the graph runs", []),
    "Shape": ("folded to a constant; the shape is fixed at export", []),
    "Size": ("folded to a constant", []),
    "Range": ("folded to a constant; the bounds are known at export", []),
    "EyeLike": ("folded to a constant identity matrix", []),
    "Trilu": ("multiply by a constant triangular mask", ["Mul"]),
    "ReverseSequence": ("reverse along an axis == Slice with a negative step, or a constant "
                        "permutation applied by MatMul", ["Slice", "MatMul"]),
    "ConcatFromSequence": ("sequences do not exist at a fixed shape; the members are known "
                           "and concatenate directly", ["Concat"]),
    "SplitToSequence": ("as Split; the sequence is unrolled at export", ["Split"]),
    "CastLike": ("a relabelling cast is removed. A VALUE-CHANGING one is refused", []),

    # --- linear algebra and transforms -------------------------------------------------------
    "Einsum": ("transpose and reshape the operands into a matrix product",
               ["Transpose", "Reshape", "MatMul"]),
    "DFT": ("at a fixed length the DFT is linear: multiply by a constant twiddle matrix",
            ["MatMul", "Concat"]),
    "STFT": ("window, then a DFT per frame; both constant at a fixed length",
             ["Mul", "MatMul", "Concat"]),
    "BlackmanWindow": ("a constant vector", []),
    "HammingWindow": ("a constant vector", []),
    "HannWindow": ("a constant vector", []),
    "MelWeightMatrix": ("a constant matrix", []),
    "MaxRoiPool": ("crop by Slice, then max pool, for a fixed set of regions",
                   ["Slice", "MaxPool", "Concat"]),
    "RoiAlign": ("bilinear sample at fixed offsets == Slice and weighted Add",
                 ["Slice", "Mul", "Add", "Concat"]),

    "TfIdfVectorizer": ("n-gram counting over TOKEN IDS, not text: the schema accepts "
                        "tensor(int32) and tensor(int64) as well as tensor(string), so with "
                        "ids in it is onehot-and-accumulate. It was refused as 'operates on "
                        "strings' until the schema was actually read",
                        ["OneHot", "MatMul", "ReduceSum"]),

    # --- loss --------------------------------------------------------------------------------
    "NegativeLogLikelihoodLoss": ("-sum(onehot(target) * logsoftmax(x))",
                                  ["OneHot", "LogSoftmax", "Mul", "ReduceSum", "Neg"]),
    "SoftmaxCrossEntropyLoss": ("as NLL over log softmax",
                                ["OneHot", "LogSoftmax", "Mul", "ReduceSum", "Neg"]),
}

#: operator -> (category, why there is no rewrite)
REFUSED = {
    # The output shape depends on the values, which a static graph cannot express.
    "Compress": ("data-dependent-shape", "the output length depends on the mask's contents"),
    "NonZero": ("data-dependent-shape", "the output length is the number of nonzeros"),
    "Unique": ("data-dependent-shape", "the output length is the number of distinct values"),
    "NonMaxSuppression": ("data-dependent-shape",
                          "the number of surviving boxes depends on the scores"),

    # Execution that branches or repeats at runtime.
    "If": ("control-flow", "both branches would have to be resident and only one taken"),
    "Loop": ("control-flow", "the trip count is not known at export"),
    "Scan": ("control-flow", "a loop carrying state between iterations"),
    "SequenceMap": ("control-flow", "a loop over a sequence"),

    # Not tensors.
    "Optional": ("not-a-tensor", "an optional-typed value, not a tensor"),
    "OptionalGetElement": ("not-a-tensor", "operates on optional types"),
    "OptionalHasElement": ("not-a-tensor", "operates on optional types"),
    "SequenceAt": ("not-a-tensor", "operates on sequence types"),
    "SequenceConstruct": ("not-a-tensor", "operates on sequence types"),
    "SequenceEmpty": ("not-a-tensor", "operates on sequence types"),
    "SequenceErase": ("not-a-tensor", "operates on sequence types"),
    "SequenceInsert": ("not-a-tensor", "operates on sequence types"),
    "SequenceLength": ("not-a-tensor", "operates on sequence types"),
    "StringNormalizer": ("not-reproducible",
                         "case folding here is LOCALE-DEPENDENT: the schema's locale "
                         "attribute is 'environment dependent', so the same graph gives "
                         "different output on different machines. That is the objection "
                         "Blender is blocklisted for and it is fatal on its own. Unicode "
                         "folding is also not length-preserving -- sharp s folds to ss, the "
                         "Turkish dotted and dotless i disagree -- so no fixed-shape tensor "
                         "operation expresses it, and folding a string as bytes is ASCII "
                         "thinking. Tokenize before the graph"),

    # A rewrite would have to invent an RNG, and a corpus from one is not reproducible.
    "Bernoulli": ("nondeterministic", "sampling; no deterministic rewrite"),
    "Multinomial": ("nondeterministic", "sampling; no deterministic rewrite"),
    "RandomNormal": ("nondeterministic", "sampling; no deterministic rewrite"),
    "RandomNormalLike": ("nondeterministic", "sampling; no deterministic rewrite"),
    "RandomUniform": ("nondeterministic", "sampling; no deterministic rewrite"),
    "RandomUniformLike": ("nondeterministic", "sampling; no deterministic rewrite"),

    # The compiler quantizes. Emitting these ourselves fights it for the same job.
    "QuantizeLinear": ("toolchain-owns-it", "the compiler performs quantization"),
    "DequantizeLinear": ("toolchain-owns-it", "the compiler performs quantization"),
    "DynamicQuantizeLinear": ("toolchain-owns-it", "the compiler performs quantization"),
    "QLinearConv": ("toolchain-owns-it", "the compiler quantizes a float Conv"),
    "QLinearMatMul": ("toolchain-owns-it", "the compiler quantizes a float MatMul"),
    "ConvInteger": ("toolchain-owns-it", "integer convolution is the compiler's output"),
    "MatMulInteger": ("toolchain-owns-it", "integer matmul is the compiler's output"),

    # A rewrite exists on paper and dies under int8. See native_onehot.py.
    "Floor": ("rounding", "a sum of clipped steps needs an amplification that int8 destroys; "
                          "measured in native_onehot.py on the same shape of reconstruction"),
    "Ceil": ("rounding", "as Floor"),
    "Round": ("rounding", "as Floor"),
    "Mod": ("rounding", "a - b * floor(a / b), and Floor is refused"),
    "Cast": ("rounding", "a relabelling cast is removed; a value-changing one is refused. "
                         "The target ACCEPTS one and does not perform it, returning an "
                         "f32 -> s32 -> f32 round trip untruncated and wrong by 0.875"),
    "BitShift": ("rounding", "integer bit manipulation on a float datapath"),

    # Genuinely hard, and honest to say so.
    "Det": ("no-known-rewrite", "a determinant of arbitrary size is not a fixed dataflow graph"),
}


def render():
    lines = ['', '    def Scope "Secondary"', '    {']
    lines.append('        custom string note = "Every opset-17 operator the target does not '
                 'implement, with either a rewrite into ones it does or a reason there is '
                 'none. Both are entries: an operator with no row would be indistinguishable '
                 'from one nobody has examined."')
    lines.append('')
    by_cat = {}
    for op in sorted(REWRITES):
        by_cat.setdefault(CATEGORY.get(op, "uncategorised"), []).append(op)

    for cat in sorted(by_cat):
        scope = "".join(w.capitalize() for w in cat.split("-"))
        lines += ['        def Scope "%s"' % scope, '        {']
        if cat == "trigonometric-approximate":
            lines.append('            custom string warning = "APPROXIMATE, and RANGE '
                         'LIMITED. These are polynomials, not identities, so they are absent '
                         "from RfdetrProofs/Secondary.lean on purpose -- a theorem claiming "
                         'equality would be false. Worse, they hold only on [-pi/2, pi/2]. '
                         'Reviewed against tinygrad codegen/decomp/transcendental.py (MIT), '
                         'itself derived from SLEEF: the POLYNOMIAL is plain multiply-add and '
                         'emits fine, but the Payne-Hanek and Cody-Waite range reductions that '
                         'make it valid everywhere rest on bitcast, shifts, frexp, ldexp and '
                         'round-to-int -- 31 casts and 6 bitcasts in that file -- and every '
                         'one of those is in Refused. So a correct sine over the reals is not '
                         'reachable on this target, and an argument outside the interval '
                         'returns a wrong number rather than an error."')
        for op in by_cat[cat]:
            identity, uses = REWRITES[op]
            seq = ", ".join('"%s"' % u for u in uses)
            lines += [
                '            def Scope "%s"' % op,
                '            {',
                '                custom string identity = "%s"' % identity.replace('"', "'"),
                '                custom token[] sequence = [%s]' % seq,
            ]
            if op in PROOF:
                lines.append('                custom token proof = "%s"' % PROOF[op])
            if op in SPEC_BODY:
                lines.append('                custom token spec_body = "%s"' % SPEC_BODY[op])
                lines.append('                custom string source = "ONNX spec FunctionProto, '
                             'Apache-2.0 -- authoritative, and it disagrees with the '
                             'hand-written identity in at least one place: the spec builds '
                             'GreaterOrEqual from Equal, Greater and Or where this table had '
                             '1 - Less. Both compute it; only one is the specification."')
            lines += [
                '            }',
                '',
            ]
        lines += ['        }', '']
    lines += ['    }', '', '    def Scope "Refused"', '    {']
    lines.append('        custom string note = "No rewrite, and the category says how '
                 'permanent that is. A data-dependent shape can never be a static graph; a '
                 'rounding refusal is a measurement that could be revisited on a wider '
                 'datapath."')
    lines.append('')
    for op in sorted(REFUSED):
        category, why = REFUSED[op]
        lines += [
            '        def Scope "%s"' % op,
            '        {',
            '            custom token category = "%s"' % category,
            '            custom string reason = "%s"' % why.replace('"', "'"),
            '        }',
            '',
        ]
    lines += ['    }', '']
    return "\n".join(lines)


def main(argv):
    body = render()
    if "--print" in argv:
        print(body)
        return 0

    path = HERE / "hailo_ops.usda"
    text = path.read_text(encoding="utf-8")
    # Drop any existing Secondary/Refused scopes, then append the freshly rendered ones.
    text = re.sub(r'\n    def Scope "(?:Secondary|Refused)"\n    \{.*?\n    \}\n',
                  "\n", text, flags=re.S)
    text = text.rstrip().rstrip("}").rstrip() + "\n" + body + "}\n"
    path.write_text(text, encoding="utf-8", newline="\n")
    print("wrote %d rewrites and %d refusals (%d operators)"
          % (len(REWRITES), len(REFUSED), len(REWRITES) + len(REFUSED)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
